services:
  - type: web
    name: khelify-backend
    env: node

    rootDir: khelify-backend   # 👈 THIS IS THE MAGIC LINE

    buildCommand: npm install
    startCommand: npm start

    envVars:
      - key: NODE_ENV
        value: production
      - key: CRICAPI_KEY
        sync: false
      - key: YOUTUBE_KEY
        sync: false
